name: Build & Test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup node 23
        uses: actions/setup-node@v5
        with:
          node-version: 23.x
      - run: npm install
      - run: npm run build
      - run: npm test
